function mostrar()
{

	var modoPago;
	var 
	var 
	var


	modoPago = prompt("ingrese su modo de pago");

	switch(modoPago)
	{
	case "tarjeta visa":
	case "mercado pago"
		descuento 
	break

	}






}
/*

CADA HABITACION DE UN HOTEL TIENE UN PRECIO, HAY PROMOCIONES SEGUN EL TPO DE PAGO, 
SI ES CON TARJETA VISA UN 10%, 
SI ES POR PAYPAL UN 15% , 
POR MERCADO PAGO UN 10% ,
EFECTIVO UN 20% 
CUALQUIERO OTRO MEDIO ES 5% 
SI COMPRASTE EL PAQUETE "TODO INCUIDO" Y PAGAS CON PAYPAL SE TE SUMA UN 10%(1.10) AL DESCUENTO

SI  PAGAS EN EFECTIVO TENES VARIAS OPCIONES EL PAQUETE "SOLO DESAYUNOS" TE SUMA UN 10% AL DESCUENTO 
SI EL PAQUETE ES "TODOINCLUIDO" TE SUMA UN 15% Y PARA EL RESTO DE LOS PAQUETES NO TIENE DESCUENTO ADICIONAL
